export const GET_PRESENTATIONS_REQUEST = "GET_PRESENTATIONS_REQUEST";
export const GET_PRESENTATIONS_SUCCESS = "GET_PRESENTATIONS_SUCCESS";
export const GET_PRESENTATIONS_FAIL = "GET_PRESENTATIONS_FAIL";

export const GET_PRESENTATION_DETAILS_REQUEST = "GET_PRESENTATION_DETAILS_REQUEST";
export const GET_PRESENTATION_DETAILS_SUCCESS = "GET_PRESENTATION_DETAILS_SUCCESS";
export const GET_PRESENTATION_DETAILS_FAIL = "GET_PRESENTATION_DETAILS_FAIL";
export const GET_PRESENTATION_DETAILS_RESET = "GET_PRESENTATION_DETAILS_RESET";